### ISSUE TITLE
Auto merge `swipl-wasm` bumps

### ISSUE THREAD

**Issue by jeswr** [eyereasoner/eye-js#1021]
Should look something like

```yml
name: Enable automerge on dependabot PRs

on:
  pull_request_target:

jobs:
  automerge:
    name: Enable automerge on dependabot PRs
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    if: github.actor == 'dependabot[bot]' && !contains(github.head_ref, 'dependabot/npm_and_yarn/swipl-wasm-')
    steps:
      - uses: actions/checkout@v4
      - run: gh pr merge ${{ github.event.pull_request.html_url }} --auto --squash
    env:
      GH_TOKEN: ${{ github.token }}
    if: github.actor == 'dependabot[bot]' && contains(github.head_ref, 'dependabot/npm_and_yarn/swipl-wasm-')
    steps:
      - uses: actions/checkout@v4
      - run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          before=$(echo $PR_TITLE | grep -oP '(?<=from )\d+\.\d+\.\d+')
          after=$(echo $PR_TITLE | grep -oP '(?<=to )\d+\.\d+\.\d+')
          
          readarray -d . -t before <<<"${before:2:-1}"
          readarray -d . -t after <<<"${current:2:-1}"

          if   [ ! ${before[0]} == ${after[0]} ]; then
            version="BREAKING CHANGE"
            branchHead="breaking"
          elif [ ! ${before[1]} == ${after[1]} ]; then
            version="feat"
            branchHead="feat"
          elif [ ! ${before[2]} == ${after[2]} ]; then
            version="fix"
            branchHead="fix"
          fi

          PR_TITLE="${PR_TITLE//build/$version}"

      - run: gh pr merge ${{ github.event.pull_request.html_url }} --auto --squash --body "$PR_TITLE"
    env:
      GH_TOKEN: ${{ github.token }}

```
